wandb_version: 1

batch_size:
  value: 32
conv_to_linear_dim:
  value: 144
epochs:
  value: 40
hidden_channel_array:
  value:
  - 4
  - 8
  - 16
hidden_dim_array:
  value:
  - 50
hidden_kernel_array:
  value:
  - 3
  - 3
  - 3
hidden_padding_array:
  value:
  - 1
  - 1
  - 1
hidden_stride_array:
  value:
  - 1
  - 1
  - 1
input_channel:
  value: 1
lr:
  value: 0.001
momentum:
  value: 0.95
non_linear_function_array:
  value: []
optimizer:
  value: adamw
output_dim:
  value: 10
regularization_array:
  value: []
weight_decay:
  value: 0.02
