wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1641485048
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 16
      4: 3.9.7
      5: 0.12.9
      8:
      - 5
model:
  desc: null
  value: '{''input_channel'': 1, ''conv_to_linear_dim'': 144, ''output_dim'': 10,
    ''hidden_channel_array'': [4, 8, 16], ''hidden_kernel_array'': [3, 3, 3], ''hidden_stride_array'':
    [1, 1, 1], ''hidden_padding_array'': [1, 1, 1], ''hidden_dim_array'': [50], ''non_linear_function_array'':
    [], ''regularization_array'': []}'
train:
  desc: null
  value: '{''batch_size'': 64, ''batch_ratio_validation'': 0.2, ''lr'': 0.001, ''epochs'':
    20, ''seed'': 1234, ''optimizer'': ''adam'', ''momentum'': 0.9, ''weight_decay'':
    0}'
